name: Audit Mirror + Digest

on:
  schedule:
    # Run daily at 02:00 UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  audit-mirror:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cockpit-ui

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: cockpit-ui/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run audit mirror + digest
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          ATLAS_TENANT_ID: ${{ secrets.ATLAS_TENANT_ID }}
          TOWER_SHARED_KEY: ${{ secrets.TOWER_SHARED_KEY }}
        run: node scripts/auditMirror.js

      - name: Upload proof artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: proof-artifacts-${{ github.run_number }}
          path: |
            proof/audit_mirror_v1.json
            proof/proof_digest_v1.json
          retention-days: 90

      - name: Commit and push proof updates
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          cd ..
          git add proof/audit_mirror_v1.json proof/proof_digest_v1.json

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore(audit): Daily mirror + digest $(date -u +%Y-%m-%d)"
            git push
          fi

      - name: Verify digest with Tower (optional)
        if: success()
        continue-on-error: true
        env:
          TOWER_API_URL: ${{ secrets.TOWER_API_URL }}
          ATLAS_KEY: ${{ secrets.ATLAS_KEY }}
        run: |
          if [ -n "$TOWER_API_URL" ] && [ -n "$ATLAS_KEY" ]; then
            echo "Verifying digest with Tower..."

            curl -X POST "$TOWER_API_URL/api/tower/verifyDigest" \
              -H "Content-Type: application/json" \
              -H "X-Atlas-Key: $ATLAS_KEY" \
              -d @../proof/proof_digest_v1.json \
              --fail-with-body || echo "Tower verification failed (non-blocking)"
          else
            echo "Tower verification skipped (credentials not configured)"
          fi

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Audit Mirror Job Failed',
              body: `Audit mirror job failed on ${new Date().toISOString()}\n\n` +
                    `**Run**: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}\n\n` +
                    `Please check logs and investigate.`,
              labels: ['audit', 'operations', 'priority-high']
            })
